#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : ko                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
about_link                                : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/logo.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : 변화가 없는데 다른 미래를 바라지 말자.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : JunYoung Park                                
your_link                                 :                     
your_city                                 : Siheung-si, Republic of Korea
email_address                             : bjy9507@gmail.com
facebook_username                         :                                           
instagram_username                        : jy_gon1
twitter_username                          : 
github_username                           : Gonjelly
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Git page
    description                           : Learn how to use Git, a version control system, to track changes in your code and collaborate with others.
    fontawesome_icon_name                 : code
    link                                  :
    
  - title                                 : Mobile page
    description                           : Explore the design and development of mobile-responsive web pages, optimized for a seamless user experience across all devices.
    fontawesome_icon_name                 : mobile
    link                                  :
    
  - title                                 : Server page
    description                           : Dive into the essentials of server management and configuration, ensuring robust and secure backend operations for your applications
    fontawesome_icon_name                 : book
    link                                  :

  - title                                 : Database
    description                           : Learn about database structures, query optimization, and data management techniques crucial for storing and retrieving information efficiently.
    fontawesome_icon_name                 : server
    link                                  :

  - title                                 : Algorithm
    description                           : Understand the logic and mathematics behind algorithms, focusing on problem-solving techniques that drive efficient software performance.
    fontawesome_icon_name                 : pen
    link                                  :
    
  - title                                 : Animation
    description                           : Discover the art of animation in web development, bringing interactivity and visual appeal to your projects through motion design.
    fontawesome_icon_name                 : star
    link                                  :

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.1

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  # pages:
  #   output: true
  #   permalink: /:path/

# Markdown rendering
markdown: kramdown
